services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: cyrene_auth
      POSTGRES_USER: cyrene
      POSTGRES_PASSWORD: taufeeq
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cyrene.ai
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: